/**
 * ${packageDescription}
 *
 * @ClassName ${entityName}DetailVo
 * @Author ${author}
*/
package ${packageName}.${moduleName}.vo;

import lombok.Data;

import java.util.Date;

/**
 * @ClassName ${entityName}DetailVo
 * @Author ${author}
 * @Date ${createDate}
 * @Description TODO
*/
@Data
public class ${entityName}DetailVo {

    private Integer id;
    private String name;
    private String code;
    private Date createDate;
    private Date updateDate;

}
